server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gabikersul/cloud-config-repo
          username:
          password:
          clone-on-start: true

  security:
    user:
      name: root
      password: s3cr3t